// System-wide enums for enterprise case management

const PRACTICE_AREAS = {
  FAMILY: 'FAMILY',
  CIVIL: 'CIVIL',
  CRIMINAL: 'CRIMINAL', 
  CORPORATE: 'CORPORATE',
  TAX: 'TAX',
  IP: 'IP',
  IMMIGRATION: 'IMMIGRATION',
  REAL_ESTATE: 'REAL_ESTATE',
  PERSONAL_INJURY: 'PERSONAL_INJURY'
};

const CASE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED',
  ON_HOLD: 'ON_HOLD',
  ARCHIVED: 'ARCHIVED'
};

const USER_ROLES = {
  USER: 'USER',
  LAWYER: 'LAWYER',
  SENIOR_LAWYER: 'SENIOR_LAWYER',
  PARALEGAL: 'PARALEGAL',
  CASE_MANAGER: 'CASE_MANAGER',
  ADMIN: 'ADMIN'
};

const AUDIT_EVENTS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CASE_CREATED: 'CASE_CREATED',
  CASE_UPDATED: 'CASE_UPDATED',
  CASE_CLOSED: 'CASE_CLOSED',
  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  PERMISSION_UPDATED: 'PERMISSION_UPDATED'
};

const PERMISSIONS = {
  VIEW_CASE: 'VIEW_CASE',
  EDIT_CASE: 'EDIT_CASE',
  CLOSE_CASE: 'CLOSE_CASE',
  UPLOAD_DOCUMENTS: 'UPLOAD_DOCUMENTS',
  SEND_MESSAGES: 'SEND_MESSAGES',
  GENERATE_INVOICES: 'GENERATE_INVOICES',
  MANAGE_ASSIGNMENTS: 'MANAGE_ASSIGNMENTS',
  APPROVE_TRANSITIONS: 'APPROVE_TRANSITIONS'
};

// Role-based permissions matrix
const ROLE_PERMISSIONS = {
  [USER_ROLES.USER]: [PERMISSIONS.VIEW_CASE, PERMISSIONS.SEND_MESSAGES],
  [USER_ROLES.LAWYER]: [PERMISSIONS.VIEW_CASE, PERMISSIONS.EDIT_CASE, PERMISSIONS.UPLOAD_DOCUMENTS, PERMISSIONS.SEND_MESSAGES, PERMISSIONS.GENERATE_INVOICES],
  [USER_ROLES.SENIOR_LAWYER]: [PERMISSIONS.VIEW_CASE, PERMISSIONS.EDIT_CASE, PERMISSIONS.CLOSE_CASE, PERMISSIONS.UPLOAD_DOCUMENTS, PERMISSIONS.SEND_MESSAGES, PERMISSIONS.GENERATE_INVOICES, PERMISSIONS.APPROVE_TRANSITIONS],
  [USER_ROLES.PARALEGAL]: [PERMISSIONS.VIEW_CASE, PERMISSIONS.UPLOAD_DOCUMENTS, PERMISSIONS.SEND_MESSAGES],
  [USER_ROLES.CASE_MANAGER]: [PERMISSIONS.VIEW_CASE, PERMISSIONS.EDIT_CASE, PERMISSIONS.MANAGE_ASSIGNMENTS, PERMISSIONS.APPROVE_TRANSITIONS],
  [USER_ROLES.ADMIN]: Object.values(PERMISSIONS)
};

module.exports = {
  PRACTICE_AREAS,
  CASE_STATUS,
  USER_ROLES,
  AUDIT_EVENTS,
  PERMISSIONS,
  ROLE_PERMISSIONS
};